Importing all the needed libraries

In [2]:
import numpy as np
import pandas as pd

Write a Python program to print the NumPy
version in your system.

In [3]:
print(np.__version__)

1.18.1


Write a Python program to reverse an array
(first element becomes last).

In [7]:
arr=np.arange(10)
print (arr)
rever=arr[::-1]
print (rever)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Write a Python program to convert a list and
tuple into arrays.

In [8]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([1, 2,], [ 2, 3],[3,4])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[1 2]
 [2 3]
 [3 4]]


Write a Python program to find common values
between two arrays.

In [10]:
array1 = np.arange(10)
print("Array1: ",array1)
array2 = np.arange(4,12)
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [0 1 2 3 4 5 6 7 8 9]
Array2:  [ 4  5  6  7  8  9 10 11]
Common values between two arrays:
[4 5 6 7 8 9]


Write a Python program compare two arrays
using numpy.

In [16]:

def comp_arrays(array1,array2):
    print("Array1: ",array1)
    print("Array2: ",array2)
    if array1.shape==array2.shape:
        if (array1==array2).all():
            print ("Arrays are equal")
        else:
            print ("Not equal")
    else:
        print ("Not equal")
        
array1 = np.arange(10)
array2 = np.arange(15)
comp_arrays(array1,array2)
arr1 = np.arange(5)
arr2 = np.arange(2,7)
comp_arrays(arr1,arr2)
ar1= np.arange(1,9,2)
ar2= np.arange(1,9,2)
comp_arrays(ar1,ar2)

Array1:  [0 1 2 3 4 5 6 7 8 9]
Array2:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Not equal
Array1:  [0 1 2 3 4]
Array2:  [2 3 4 5 6]
Not equal
Array1:  [1 3 5 7]
Array2:  [1 3 5 7]
Arrays are equal


Write a Python program to change the
dimension of an array.

In [23]:
arr1=np.array([1,2,3,4,5,6,7,8])
print (arr1)
arr1.resize(2,4)
print (arr1)
arr1.resize(4,2)
print (arr1)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Write a Python program (using numpy) to sum
of all the multiples of 3 or 5 below 100.

In [26]:
arr = np.arange(1, 100)
mult_li= arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(mult_li)
print(mult_li.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


Write a Python program to convert a NumPy
array into Python list structure.

In [27]:
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]


Write a Python program to how to add an extra
column to a numpy array.

In [29]:
x = np.array([[1,2,3], [5,6,7]])
y = np.array([[4], [8]])
print(np.append(x, y, axis=1))

[[1 2 3 4]
 [5 6 7 8]]


Write a Python program to check whether the
numpy array is empty or not.

In [31]:
arr1=np.arange(10)
def is_empty(arr):
    if arr.size==0:
        print ("Empty")
    else:
        print ("Not Empty")
is_empty(arr1)
arr2=np.array([])
is_empty(arr2)

Not Empty
Empty


Write a Python program to normalize a 3x3
random matrix.

In [36]:
x= np.arange(-3,3)
x.resize(2,3)
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[-3 -2 -1]
 [ 0  1  2]]
After normalization:
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


How to ignore all numpy warnings (not
recommended)?

In [37]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

How to swap two rows of an array?

In [39]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [1,3,9]])
print (a)
a[[0,1,2,3]]=a[[1,3,0,2]]
print (a)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 9]]
[[4 5 6]
 [1 3 9]
 [1 2 3]
 [7 8 9]]


Compute bootstrapped 95% confidence
intervals for the mean of a 1D array X (i.e.,
resample the elements of an array with
replacement N times, compute the mean of
each sample, and then compute percentiles
over the means).

In [40]:
x = np.concatenate([np.random.exponential(size=200), np.random.normal(size=100)])
n = len(x)
reps = 10000
xb = np.random.choice(x, (n, reps))
mb = xb.mean(axis=0)
mb.sort()

np.percentile(mb, [2.5, 97.5])

array([0.49719457, 0.76531112])

Python program to create a random vector of
size 10 and sort it.

In [41]:
vec = np.random.random(10)
print("Original vector:")
print(vec)
vec.sort()
print("Sorted vector:")
print(vec)

Original vector:
[0.69719718 0.26298021 0.64456754 0.55957366 0.95958168 0.69637999
 0.99587473 0.96697789 0.94046328 0.68762433]
Sorted vector:
[0.26298021 0.55957366 0.64456754 0.68762433 0.69637999 0.69719718
 0.94046328 0.95958168 0.96697789 0.99587473]


Write a Python program to check two random
arrays are equal or not.

In [42]:
def comp_arrays(array1,array2):
    print("Array1: ",array1)
    print("Array2: ",array2)
    if array1.shape==array2.shape:
        if (array1==array2).all():
            print ("Arrays are equal")
        else:
            print ("Not equal")
    else:
        print ("Not equal")
        
array1 = np.arange(10)
array2 = np.arange(15)
comp_arrays(array1,array2)
arr1 = np.arange(5)
arr2 = np.arange(2,7)
comp_arrays(arr1,arr2)
ar1= np.arange(1,9,2)
ar2= np.arange(1,9,2)
comp_arrays(ar1,ar2)

Array1:  [0 1 2 3 4 5 6 7 8 9]
Array2:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Not equal
Array1:  [0 1 2 3 4]
Array2:  [2 3 4 5 6]
Not equal
Array1:  [1 3 5 7]
Array2:  [1 3 5 7]
Arrays are equal


Write a Python program to add, subtract,
multiply, divide arguments element-wise.

In [45]:
arr1=np.arange(8,16)
arr2=np.arange(1,9)
arr1.resize(2,4)
arr2.resize(2,4)
print (arr1)
print (arr2)
print (arr1+arr2)
print (arr1-arr2)
print (arr1*arr2)
print (arr1/arr2)

[[ 8  9 10 11]
 [12 13 14 15]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 11 13 15]
 [17 19 21 23]]
[[7 7 7 7]
 [7 7 7 7]]
[[  8  18  30  44]
 [ 60  78  98 120]]
[[8.         4.5        3.33333333 2.75      ]
 [2.4        2.16666667 2.         1.875     ]]


Write a Python program to get the dates of
yesterday, today and tomorrow.

In [46]:
last_day = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday's Date: ",last_day)
today     = np.datetime64('today', 'D')
print("Today's Date: ",today)
next_day  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's Date: ",next_day)

Yesterday's Date:  2020-07-09
Today's Date:  2020-07-10
Tomorrow's Date:  2020-07-11
